#!/usr/bin/env bash
# Render Formula/knaix.rb for the kovalentai/homebrew-tap repo.
#
#   scripts/render-tap-formula.sh [version] [output-path]
#
# Both arguments are optional. Version defaults to whatever
# releases.knaix.com currently serves, output defaults to stdout.
#
# The S3 publish is a manual step (see "Releasing the Knaix CLI" in the
# kovalent repo), so this script must assume the artifacts are not there yet
# and refuses to render a formula pointing at anything it cannot download.
#
# Exit codes:
#   0  formula rendered
#   1  something is wrong (a checksum does not match its binary)
#   3  not ready yet: the release has not been published to S3
set -euo pipefail

RELEASES="${KNAIX_RELEASES_URL:-https://releases.knaix.com}"
PLATFORMS=(darwin-arm64 darwin-x86_64 linux-arm64 linux-x86_64)
NOT_READY=3

version="${1:-}"
out="${2:-}"

note() { printf '%s\n' "$*" >&2; }

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

published="$(curl -fsSL "${RELEASES}/latest-version" | tr -d '[:space:]')" \
  || { note "Could not read ${RELEASES}/latest-version."; exit "$NOT_READY"; }

[ -n "$published" ] || { note "${RELEASES}/latest-version is empty."; exit "$NOT_READY"; }

version="${version:-$published}"
version="${version#v}"

# The formula must never get ahead of the installer. If latest-version still
# points at the previous release, the manual publish has not finished, and a
# bump now would send brew users to a version the curl installer does not yet
# serve -- or to binaries that are not uploaded at all.
if [ "$version" != "$published" ]; then
  note "Not ready: asked for ${version}, but ${RELEASES}/latest-version still serves ${published}."
  exit "$NOT_READY"
fi

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT INT TERM

# Verified checksums go to files rather than an associative array: macOS still
# ships bash 3.2, and a command substitution could not exit the script from the
# loop anyway.
for platform in "${PLATFORMS[@]}"; do
  binary_url="${RELEASES}/v${version}/knaix-${platform}"
  sidecar_url="${binary_url}.sha256"

  if ! curl -fsSL -o "${work}/${platform}" "$binary_url"; then
    note "Not ready: ${binary_url} is not reachable."
    exit "$NOT_READY"
  fi
  if ! curl -fsSL -o "${work}/${platform}.sha256" "$sidecar_url"; then
    note "Not ready: ${sidecar_url} is not reachable."
    exit "$NOT_READY"
  fi

  expected="$(tr -d '[:space:]' < "${work}/${platform}.sha256")"
  actual="$(sha256_of "${work}/${platform}")"

  # Recomputed from the bytes rather than copied from the sidecar. Trusting the
  # sidecar would happily bake in the checksum of a truncated upload, and brew
  # would then verify a broken binary against its own broken hash.
  if [ "$expected" != "$actual" ]; then
    note "Checksum mismatch for knaix-${platform}: sidecar says ${expected}, the binary is ${actual}."
    exit 1
  fi

  printf '%s' "$actual" > "${work}/${platform}.verified"
done

note "All ${#PLATFORMS[@]} platforms verified at v${version}."

sha_darwin_arm64="$(cat "${work}/darwin-arm64.verified")"
sha_darwin_x86_64="$(cat "${work}/darwin-x86_64.verified")"
sha_linux_arm64="$(cat "${work}/linux-arm64.verified")"
sha_linux_x86_64="$(cat "${work}/linux-x86_64.verified")"

read -r -d '' formula <<EOF || true
# Generated by knaix-cli's tap-bump workflow. Edit that template, not this file.
class Knaix < Formula
  desc "Command-line client for Kovalent: private AI nodes with cited answers"
  homepage "https://knaix.com"
  version "${version}"
  license "Apache-2.0"

  # No livecheck block. It cannot pass brew style here: with no top-level url,
  # the LivecheckUrlSymbol cop reads livecheck's own url as the stable one and
  # demands \`url :stable\`, while ComponentsOrder demands livecheck sit above the
  # on_macos block where that happens. CI compares this version against
  # releases.knaix.com/latest-version instead, which fails louder anyway.

  on_macos do
    on_arm do
      url "${RELEASES}/v${version}/knaix-darwin-arm64"
      sha256 "${sha_darwin_arm64}"
    end
    on_intel do
      url "${RELEASES}/v${version}/knaix-darwin-x86_64"
      sha256 "${sha_darwin_x86_64}"
    end
  end

  on_linux do
    on_arm do
      url "${RELEASES}/v${version}/knaix-linux-arm64"
      sha256 "${sha_linux_arm64}"
    end
    on_intel do
      url "${RELEASES}/v${version}/knaix-linux-x86_64"
      sha256 "${sha_linux_x86_64}"
    end
  end

  def install
    # The published artifacts are bare binaries rather than archives, so the
    # staged file is renamed onto PATH instead of extracted. It arrives 0644
    # from the bucket and install keeps that mode, so set it before anything
    # tries to run the binary.
    bin.install Dir["knaix-*"].first => "knaix"
    chmod 0755, bin/"knaix"
    generate_completions_from_executable(bin/"knaix", "completions")
  end

  def caveats
    <<~EOS
      Start a node on this machine:
        knaix local setup

      Or sign in to a node Kovalent runs for you:
        knaix login
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/knaix --version")
    assert_match "_knaix", shell_output("#{bin}/knaix completions bash")
  end
end
EOF

if [ -n "$out" ]; then
  printf '%s\n' "$formula" > "$out"
  note "Wrote ${out}."
else
  printf '%s\n' "$formula"
fi
