//! Shell integration: paint the `knaix` wordmark as the user types it.
//!
//! This is opt-in by design. A CLI that silently edits a shell profile is
//! doing the one thing our own positioning says we do not do, and a hook that
//! misbehaves breaks the user's line editor rather than merely our output. So
//! the integration is printed, the user installs it, and `--install` exists to
//! make that one guided command rather than a copy-paste job.
//!
//! What gets installed is a single `eval` line, not the snippet itself. The
//! snippet is regenerated from this binary on every shell start, so upgrading
//! the CLI upgrades the integration and a dotfile can never hold a stale copy
//! of the gradient.

use anyhow::{bail, Result};
use std::path::PathBuf;

/// Shells we can paint the wordmark in.
#[derive(Debug, Clone, Copy, PartialEq, Eq, clap::ValueEnum)]
pub enum InitShell {
    Zsh,
}

/// Fences the installed line so `--install` is idempotent and `--uninstall`
/// knows exactly what it put there.
const BEGIN_MARK: &str = "# >>> knaix shell integration >>>";
const END_MARK: &str = "# <<< knaix shell integration <<<";

/// The line a profile actually gets. Regenerating on shell start is the whole
/// point: the dotfile holds a reference, never a copy.
fn eval_line(shell: InitShell) -> String {
    match shell {
        InitShell::Zsh => r#"eval "$(knaix shell-init zsh)""#.to_string(),
    }
}

/// The integration script for `shell`.
pub fn init_script(shell: InitShell) -> Result<String> {
    match shell {
        InitShell::Zsh => Ok(zsh_script()),
    }
}

fn zsh_script() -> String {
    let n = crate::brand::WORDMARK.chars().count();
    let hex = crate::brand::ramp_hex();
    let cube = crate::brand::ramp_256();

    // Both ramps are written out, and the snippet picks between them at shell
    // start rather than at generation time: the user may open the same profile
    // in a different terminal tomorrow.
    let hex_list = hex
        .iter()
        .map(|c| format!("'fg={c}'"))
        .collect::<Vec<_>>()
        .join(" ");
    let cube_list = cube
        .iter()
        .map(|c| format!("'fg={c}'"))
        .collect::<Vec<_>>()
        .join(" ");

    format!(
        r#"# knaix shell integration. Generated by `knaix shell-init zsh`; do not edit.
#
# Paints the `{word}` wordmark in the brand gradient as you type it.
#
# zsh-syntax-highlighting, if you use it, styles a recognised command with one
# colour, and one style cannot express a per-letter ramp. This appends its own
# spans to region_highlight afterwards instead, so it layers over that plugin
# rather than fighting it. It also works fine on its own without that plugin.

# The interactive guard is load-bearing. `add-zle-hook-widget` fails where
# there is no line editor, and a profile whose last command failed leaves a
# non-zero $? at the first prompt. Themes read that: robbyrussell, oh-my-zsh's
# default, renders its arrow red on a non-zero status, so without this a user
# would open every new terminal to what looks like an error.
if [[ -n ${{ZSH_VERSION-}} ]] && [[ -o interactive ]]; then
  if [[ $COLORTERM == (truecolor|24bit) ]]; then
    _knaix_ramp=( {hex_list} )
  else
    # No 24-bit colour here. These are the same cube entries the CLI itself
    # falls back to, so the prompt and the program agree.
    _knaix_ramp=( {cube_list} )
  fi

  _knaix_highlight_wordmark() {{
    emulate -L zsh
    local rest=$BUFFER
    local -i off=0 s i
    # Every occurrence, not only the command word: this is what gradients the
    # first five letters of `{word}dev` and leaves the rest alone.
    while [[ -n $rest && $rest =~ '{word}' ]]; do
      s=$(( off + MBEGIN - 1 ))   # region_highlight is 0-based, end-exclusive
      for (( i = 1; i <= {n}; i++ )); do
        region_highlight+=( "$(( s + i - 1 )) $(( s + i )) ${{_knaix_ramp[i]}}" )
      done
      off=$(( off + MEND ))
      rest=${{rest[$(( MEND + 1 )),-1]}}
    done
  }}

  autoload -Uz add-zle-hook-widget
  add-zle-hook-widget zle-line-pre-redraw _knaix_highlight_wordmark 2>/dev/null
fi

# Always succeed. Same reasoning as the guard above: this line is the last thing
# an `eval` in a profile runs, and its status is what the first prompt sees.
true
"#,
        word = crate::brand::WORDMARK,
    )
}

/// Where `shell` reads its interactive configuration from.
fn profile_path(shell: InitShell) -> Result<PathBuf> {
    match shell {
        InitShell::Zsh => {
            // ZDOTDIR is the supported way to move a zsh config, and a user who
            // set it will not thank us for writing to ~ anyway.
            if let Some(dir) = std::env::var_os("ZDOTDIR") {
                return Ok(PathBuf::from(dir).join(".zshrc"));
            }
            match home::home_dir() {
                Some(h) => Ok(h.join(".zshrc")),
                None => bail!("Could not locate your home directory to find .zshrc"),
            }
        }
    }
}

/// True when the profile already carries our block.
fn already_installed(contents: &str) -> bool {
    contents.contains(BEGIN_MARK)
}

/// The fenced block written into a profile.
fn block(shell: InitShell) -> String {
    format!("{BEGIN_MARK}\n{}\n{END_MARK}\n", eval_line(shell))
}

/// Remove a previously installed block, returning the new contents.
fn strip_block(contents: &str) -> String {
    let mut out = String::with_capacity(contents.len());
    let mut skipping = false;
    for line in contents.lines() {
        if line.trim() == BEGIN_MARK {
            skipping = true;
            continue;
        }
        if line.trim() == END_MARK {
            skipping = false;
            continue;
        }
        if !skipping {
            out.push_str(line);
            out.push('\n');
        }
    }
    out
}

/// Add the integration to the user's profile, after they agree to it.
pub fn install(shell: InitShell) -> Result<()> {
    use colored::*;
    use dialoguer::{theme::ColorfulTheme, Confirm};
    use std::io::IsTerminal;

    let path = profile_path(shell)?;
    let existing = std::fs::read_to_string(&path).unwrap_or_default();

    if already_installed(&existing) {
        println!(
            "{} {} already loads the {} integration. Nothing to do.",
            "✓".green(),
            path.display().to_string().cyan(),
            crate::brand::wordmark()
        );
        return Ok(());
    }

    println!(
        "\nThis adds the following to {}:\n",
        path.display().to_string().cyan()
    );
    for line in block(shell).lines() {
        println!("  {}", line.dimmed());
    }
    println!(
        "\n{}\n",
        "It loads the integration from this binary at shell start, so upgrading the CLI upgrades it."
            .dimmed()
    );

    // A prompt nobody can answer is not consent. Without a terminal, say what
    // to do rather than assuming a yes.
    if !std::io::stdin().is_terminal() {
        println!(
            "{} Not running interactively, so nothing was changed. Add the line above by hand, or run this again from a terminal.",
            "Info:".cyan()
        );
        return Ok(());
    }

    let ok = Confirm::with_theme(&ColorfulTheme::default())
        .with_prompt("Add it?")
        .default(true)
        .interact()?;

    if !ok {
        println!("{} Left {} unchanged.", "Info:".cyan(), path.display());
        return Ok(());
    }

    // Back up before touching a file we did not write. Restoring a profile from
    // memory at 2am is a bad evening.
    if !existing.is_empty() {
        let backup = path.with_extension(format!(
            "knaix-backup-{}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_secs())
                .unwrap_or(0)
        ));
        std::fs::write(&backup, &existing)?;
        println!("{} Backed up to {}", "Info:".cyan(), backup.display());
    }

    let mut next = existing;
    if !next.is_empty() && !next.ends_with('\n') {
        next.push('\n');
    }
    next.push('\n');
    next.push_str(&block(shell));
    std::fs::write(&path, next)?;

    println!(
        "{} Installed. Run {} to see it.",
        "✓".green(),
        "source ~/.zshrc".cyan()
    );
    Ok(())
}

/// Take the integration back out.
pub fn uninstall(shell: InitShell) -> Result<()> {
    use colored::*;

    let path = profile_path(shell)?;
    let existing = std::fs::read_to_string(&path).unwrap_or_default();

    if !already_installed(&existing) {
        println!("{} No knaix block in {}.", "Info:".cyan(), path.display());
        return Ok(());
    }

    std::fs::write(&path, strip_block(&existing))?;
    println!(
        "{} Removed the knaix block from {}. Open a new shell to apply.",
        "✓".green(),
        path.display()
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn script_carries_the_generated_ramp() {
        let s = init_script(InitShell::Zsh).unwrap();
        // Both ramps are present so the snippet can choose at shell start.
        for hex in crate::brand::ramp_hex() {
            assert!(s.contains(&format!("fg={hex}")), "missing {hex}");
        }
        for idx in crate::brand::ramp_256() {
            assert!(s.contains(&format!("fg={idx}")), "missing index {idx}");
        }
    }

    #[test]
    fn script_is_guarded_so_a_non_zsh_shell_ignores_it() {
        let s = init_script(InitShell::Zsh).unwrap();
        assert!(s.contains("ZSH_VERSION"));
        assert!(s.contains("-o interactive"));
    }

    #[test]
    fn script_ends_by_succeeding() {
        // The eval's status is what the first prompt sees, and oh-my-zsh's
        // default theme paints its arrow red on a non-zero one.
        let s = init_script(InitShell::Zsh).unwrap();
        let last = s.lines().rfind(|l| !l.trim().is_empty()).unwrap();
        assert_eq!(last.trim(), "true");
    }

    #[test]
    fn installed_block_references_rather_than_copies() {
        // The point of the eval line: a profile holds a reference, so the
        // snippet cannot go stale when the brand gradient is retuned.
        let b = block(InitShell::Zsh);
        assert!(b.contains(r#"eval "$(knaix shell-init zsh)""#));
        for hex in crate::brand::ramp_hex() {
            assert!(!b.contains(&hex), "the block must not inline colours");
        }
    }

    #[test]
    fn detects_an_existing_install() {
        assert!(!already_installed("alias ls='ls -G'\n"));
        assert!(already_installed(&format!(
            "x\n{}\n",
            block(InitShell::Zsh)
        )));
    }

    #[test]
    fn strip_removes_only_our_block() {
        let before = format!(
            "alias python=python3\n\n{}\nexport PATH=/x:$PATH\n",
            block(InitShell::Zsh)
        );
        let after = strip_block(&before);
        assert!(after.contains("alias python=python3"));
        assert!(after.contains("export PATH=/x:$PATH"));
        assert!(!after.contains(BEGIN_MARK));
        assert!(!after.contains("shell-init"));
    }

    #[test]
    fn install_then_strip_round_trips() {
        let original = "alias python=python3\nexport PATH=/x:$PATH\n";
        let installed = format!("{original}\n{}", block(InitShell::Zsh));
        // Stripping restores the original lines, whitespace aside.
        let stripped = strip_block(&installed);
        let norm = |s: &str| {
            s.lines()
                .filter(|l| !l.trim().is_empty())
                .collect::<Vec<_>>()
                .join("\n")
        };
        assert_eq!(norm(&stripped), norm(original));
    }
}
